# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from kr.re.keit import Komoran_pb2 as kr_dot_re_dot_keit_dot_Komoran__pb2


class KomoranStub(object):
    """Missing associated documentation comment in .proto file"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.tokenize = channel.unary_unary(
                '/kr.re.keit.Komoran/tokenize',
                request_serializer=kr_dot_re_dot_keit_dot_Komoran__pb2.TokenizeRequest.SerializeToString,
                response_deserializer=kr_dot_re_dot_keit_dot_Komoran__pb2.TokenizeResponse.FromString,
                )


class KomoranServicer(object):
    """Missing associated documentation comment in .proto file"""

    def tokenize(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_KomoranServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'tokenize': grpc.unary_unary_rpc_method_handler(
                    servicer.tokenize,
                    request_deserializer=kr_dot_re_dot_keit_dot_Komoran__pb2.TokenizeRequest.FromString,
                    response_serializer=kr_dot_re_dot_keit_dot_Komoran__pb2.TokenizeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kr.re.keit.Komoran', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Komoran(object):
    """Missing associated documentation comment in .proto file"""

    @staticmethod
    def tokenize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/kr.re.keit.Komoran/tokenize',
            kr_dot_re_dot_keit_dot_Komoran__pb2.TokenizeRequest.SerializeToString,
            kr_dot_re_dot_keit_dot_Komoran__pb2.TokenizeResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
